env:
  browser: true
  es2020: true
extends: 
  ['eslint:recommended','plugin:jest/recommended']
plugins:
  ['jest']
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
ignorePatterns:
  ['src/assets/scripts/dev.js']
