version: 2
jobs:
    build:
        docker:
            - image: circleci/node:12.18.3
        
        branches:
            only:
                - master

        working_directory: ~/build

        steps:
            - checkout
            - run: sudo npm install -g gulp
            - run: npm install
            - run: npx jest --config=jest.config.js
            - run: gulp build
            - run: ./.circleci/deploy.sh
