version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.13
        
        branches:
            only:
                - master

        working_directory: ~/build

        steps:
            - checkout
            - run: sudo npm install -g gulp
            - run: npm install
            - run: gulp build
            - run: cd dist
            - run: ./../.circleci/deploy.sh
