name: CD

on:
  push:
    branches: [ "master" ]
    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: deploy
        run: |
          sudo npm install -g gulp
          npm install
          npx jest --config=jest.config.js
          gulp build
          ./.circleci/deploy.sh
